Updated content for the intro description of E^0
ubcengineers/weeke0-2018 pull request #1
Opened 2018-06-26 14:05 UTC by juliannaweldon

Changed wording slightly - less awkward and made it sound slightly more exciting. (hopefully)

2018-06-26 16:09 UTC, qgolsteyn requested changes

2018-06-26 16:09 UTC, qgolsteyn commented on src/components/about/index.js
> +                        BBQs, movie nights, pancake breakfasts, and some crazy traditions to be a part of!It’s our grand opening bash, so start off
Small typo: space missing between "to be a part of!It's our grand opening"

2018-06-26 16:09 UTC, qgolsteyn commented on src/components/about/index.js
> +                        engineering student teams and clubs.  We hope to see you around!
Double space before "We hope to see you around!"

2018-06-26 16:09 UTC, qgolsteyn commented on src/components/about/index.js
> +                        week will be a little less hectic, but don’t miss the info session for E-Retreat or the chance to interact with UBC’s various
Thought: maybe let's not mention that the second week is less hectic?

2018-06-27 01:45 UTC, juliannaweldon commented
Made the changes requested.

2018-06-27 01:52 UTC, merged

2018-06-27 01:52 UTC, qgolsteyn commented
Thanks!